// Warstwa zapasowa: mapowanie oryginalnych kategorii bankowych na nasze drzewo.
// Używana tylko wtedy, gdy żadna reguła nie dopasowała transakcji.
export const BANK_CATEGORY_MAP: Record<string, string> = {
  // --- mBank ---
  'Żywność i chemia domowa': 'zywnosc',
  'Jedzenie poza domem': 'jedzenie_poza',
  'Alkohol': 'alkohol',
  'Przejazdy': 'przejazdy',
  'Parking i opłaty': 'parking',
  'Paliwo': 'paliwo',
  'Ubezpieczenie auta': 'auto_ubezpieczenie',
  'Podróże i wyjazdy': 'podroz_inne',
  'Sport i hobby': 'sport',
  'Wyjścia i wydarzenia': 'rozrywka',
  'Rozrywka - inne': 'rozrywka',
  'Zdrowie i uroda': 'zdrowie_opieka',
  'Odzież i obuwie': 'ubrania',
  'Elektronika': 'elektronika',
  'Akcesoria i wyposażenie': 'dom_wyposazenie',
  'Remont i ogród': 'dom_remont',
  'Art. dziecięce i zabawki': 'dzieci_inne',
  'Dzieci - inne': 'dzieci_inne',
  'Multimedia, książki i prasa': 'ksiazki',
  'Opłaty i odsetki': 'oplaty_bankowe',
  'TV, internet, telefon': 'telekom',
  'Prezenty i wsparcie': 'prezenty',
  'Zwierzęta': 'zwierzeta',
  'Wypłata gotówki': 'gotowka',
  'Osobiste - inne': 'inne',
  'Płatności - inne': 'inne',
  'Wpływy - inne': 'przychod_inny',
  'Spłata karty kredytowej': 'transfer_wlasny',
  // --- Pekao ---
  'Artykuły spożywcze': 'zywnosc',
  'Restauracje i kawiarnie': 'jedzenie_poza',
  'Puby i kluby': 'rozrywka',
  'Kino i teatr': 'rozrywka',
  'Hotele': 'podroz_nocleg',
  'Bilety lotnicze': 'podroz_loty',
  'Podróże': 'podroz_inne',
  'Taxi': 'przejazdy',
  'Transport publiczny': 'przejazdy',
  'Myjnia, przeglądy i naprawy': 'auto_serwis',
  'Naprawy i remonty': 'dom_remont',
  'Ogród': 'dom_remont',
  'Wyposażenie': 'dom_wyposazenie',
  'Opieka medyczna': 'zdrowie_opieka',
  'Lekarstwa': 'zdrowie_leki',
  'Kosmetyki': 'uroda',
  'Ubrania': 'ubrania',
  'Obuwie': 'ubrania',
  'Sport': 'sport',
  'Hobby': 'hobby',
  'Książki': 'ksiazki',
  'Multimedia': 'ksiazki',
  'Ubezpieczenia': 'ubezpieczenia',
  'Internet, TV, telefon': 'telekom',
  'Opłaty bankowe': 'oplaty_bankowe',
  'Wypłata z bankomatu': 'gotowka',
  'Zakupy przez internet': 'zakupy_online',
  'Zakupy w internecie': 'zakupy_online',
  'Podatki': 'podatek_pit',
  'Przelew wewnętrzny': 'transfer_wlasny',
  'Odsetki, zwrot z inwestycji': 'przychod_inny',
};
